Task/add css setup
scokljat/welcome-bot-frontend pull request #1
Opened 2022-03-07 14:02 UTC by scokljat

### Changes

-
-

### Reference
https://trello.com/c/1imr7GaN/3-global-style-definition-sass

2022-03-08 14:08 UTC, josip2312 requested changes

2022-03-08 14:08 UTC, josip2312 commented on src/style/abstracts/_mixins.scss
> +}
This is not used currently
```suggestion
// modal

@mixin select_label {
  position: absolute;
  top: -21%;
  left: 2%;
  color: var(--gray-60);
  font-size: 12px;
  font-weight: 500;
  padding: 2px 6px;
  background-color: var(--white-100);
}
```

2022-03-08 22:16 UTC, thedev966 commented on src/style/base/_root.scss
> +}
Pay attention to all colors and their respective changes in light vs dark mode. Include all colors that are changing in dark class.

2022-03-09 08:03 UTC, thedev966 approved these changes

2022-03-09 08:08 UTC, josip2312 approved these changes

2022-03-09 11:05 UTC, merged