Features/log in page
scokljat/welcome-bot-frontend pull request #21
Opened 2022-03-21 08:02 UTC by scokljat

## Changes

-Use "vue3-google-oauth2" package for authentication.
-Add authentication service.

## Reference
https://trello.com/c/uNZDujyz/48-task-features-loginpage

2022-03-21 12:56 UTC, thedev966 commented on src/main.js
> +  clientId: '808924355914-8k4928tljobpmqc276b5iqa60fshkubi',
Use .env variable instead.

2022-03-21 12:58 UTC, thedev966 commented on src/pages/LoginPage.vue
> +    <button @click="handleClickSignIn">
Maybe name it `handleSignIn` instead?

2022-03-21 12:59 UTC, thedev966 commented on src/store/index.js
> +      state.token = { token };
`state.token = token`

2022-03-22 09:11 UTC, thedev966 approved these changes

2022-03-22 09:11 UTC, josip2312 requested changes

2022-03-22 09:11 UTC, josip2312 commented on src/api/services/LogInService.js
> +const AuthService = {
Your file name and service name don't match

2022-03-22 09:11 UTC, josip2312 commented on src/main.js
> +  clientId: '808924355914-8k4928tljobpmqc276b5iqa60fshkubi',
Agreed

2022-03-22 09:11 UTC, josip2312 commented on src/pages/LoginPage.vue
> +    <button @click="handleClickSignIn">
Agreed

2022-03-22 09:11 UTC, josip2312 commented on src/pages/LoginPage.vue
> +  height: 4.4rem;
This does not seem right, a fixed width and height should be set very rarely on an element

2022-03-22 10:06 UTC, josip2312 commented
Address all the recommended changes

2022-03-22 12:00 UTC, josip2312 approved these changes

2022-03-22 12:00 UTC, merged