Task/messages api
scokljat/welcome-bot-frontend pull request #29
Opened 2022-03-28 13:07 UTC by thedev966

2022-03-29 10:55 UTC, scokljat approved these changes

2022-03-29 14:16 UTC, josip2312 commented on src/api/services/MessagesService.js
> +      );
Extract this to a variable
```suggestion
      const response = await axios.get(url);
```

2022-03-29 14:17 UTC, josip2312 commented on src/components/AppInput.vue
> +      :value="value"
https://vuejs.org/guide/components/events.html#usage-with-v-model

2022-03-29 14:17 UTC, josip2312 commented on src/pages/MessagesPage.vue
>        console.log(row);
```suggestion
```

2022-03-29 14:19 UTC, josip2312 commented on src/store/index.js
> +      console.log(response);
```suggestion
```

2022-03-29 14:21 UTC, josip2312 commented on src/store/index.js
> +    },
You won't need this once new logic is implemented

2022-03-29 14:22 UTC, josip2312 commented on src/store/index.js
> +      console.log(response);
```suggestion
      const response = await MessagesService.editMessage(id, message);
      
      commit(UPDATE_MESSAGE, { id, updatedMessage: response });
      commit(CLOSE_APP_MODAL);
```

2022-04-01 06:57 UTC, josip2312 requested changes

2022-04-01 06:57 UTC, josip2312 commented on src/api/services/MessagesService.js
> +      return response.data;
This is more subjective, in general it is a good practice to seperate return statements with a new line 
```suggestion
      const response = await axios.get(url);
      
      return response.data;
```

2022-04-01 06:57 UTC, josip2312 commented on src/components/AppButton.vue
> +    isSubmit: {
You don't need this `isSubmit` prop, you can just pass the type to the component directly and the root element will inherit that attribute 
https://vuejs.org/guide/components/attrs.html#attribute-inheritance

2022-04-01 06:57 UTC, josip2312 commented on src/components/AppButton.vue
> +      if (!this.isSubmit) {
It would be best if this component just emitted an event and a parent component that handles logic did the necessary action

2022-04-01 06:57 UTC, josip2312 commented on src/components/AppModal.vue
> +    },
This is not used, you can add an eslint rule that warns you if there are unused properties
https://eslint.vuejs.org/rules/no-unused-properties.html#options

2022-04-01 06:57 UTC, josip2312 commented on src/store/index.js
> +const formatMessages = (response) => {
This name would make more sense since this function is not aware of any api related stuff
```suggestion
const formatMessages = (messages) => {
```

2022-04-01 06:57 UTC, josip2312 commented on src/store/index.js
> +    [REMOVE_MESSAGE]: (state, payload) => {
You could use id here to make it more readable
```suggestion
    [REMOVE_MESSAGE]: (state, id) => {
```

2022-04-01 06:57 UTC, josip2312 commented on src/store/index.js
> +    [UPDATE_MESSAGE]: (state, payload) => {
Use destructuring here
```suggestion
    [UPDATE_MESSAGE]: (state, { id, updatedMessage} ) => {
```

2022-04-01 11:11 UTC, josip2312 approved these changes

2022-04-01 11:16 UTC, merged