Features/sidebar
scokljat/welcome-bot-frontend pull request #3
Opened 2022-03-09 11:35 UTC by scokljat

## Changes 
-Add animated and responsive sidebar with style. 
-Use a custom component  router-link to create links. 

## Reference
https://trello.com/c/JxLA7Sge/32-task-features-sidebar

2022-03-10 11:14 UTC, josip2312 requested changes

2022-03-10 11:14 UTC, josip2312 commented on src/components/TheSidebar.vue
> +.sidebarlink {
This class makes no semantic sense, it is the wrapper of sidebar links, so name it appropriately

2022-03-10 11:14 UTC, josip2312 commented on src/components/TheSidebar.vue
> +.collapsed {
This would make sense to be in the `sidebar` selector

2022-03-10 11:14 UTC, josip2312 commented on src/components/TheSidebar.vue
> +  <div class="sidebar" :class="{ collapsed: collapsed }">
```suggestion
  <div class="sidebar" :class="{ collapsed }">
```

2022-03-10 12:24 UTC, thedev966 commented on src/components/TheSidebar.vue
> +    <div class="sidebarlink">
You may want to change the class name into "sidebar_link" or "sidebarLInk" depending on what convention you follow.

2022-03-10 12:24 UTC, thedev966 commented on src/components/TheSidebar.vue
> +  transition: 0.2s linear;
Maybe it's better to option to use "ease", "ease-in" transition style instead of "linear"?

2022-03-10 13:35 UTC, thedev966 approved these changes

2022-03-11 08:16 UTC, josip2312 commented
Two things to address 
- have you agreed on a convention for class naming
- when changing routes on desktop, you are unnecessarily calling the `toggleSidebar` method on each click

2022-03-14 10:13 UTC, josip2312 approved these changes

2022-03-14 10:36 UTC, merged