Task/schedules api
scokljat/welcome-bot-frontend pull request #30
Opened 2022-03-28 13:11 UTC by scokljat

## Changes
-Add function for format date with date-fns library.
-Add schedule services,actions and mutations  for fetching, creating, editing and deleting schedules. 

## Reference 
https://trello.com/c/rhzMld7v/74-task-task-schedulesapi

2022-03-29 06:53 UTC, thedev966 commented on src/components/ModalCreateSchedule.vue
> +      else this.active = false;
Use `this.active = schedule.active === 'Active ?  true : false` instead.

2022-03-29 06:59 UTC, thedev966 approved these changes

2022-03-29 14:08 UTC, josip2312 requested changes
Here's the first round :smile:

2022-03-29 14:08 UTC, josip2312 commented on src/pages/SchedulesPage.vue
> +    this.fetchSchedules({ pageNumber: 1 });
Use vuex bound value here
```suggestion
    this.fetchSchedules({ pageNumber: pagination.page });
```

2022-03-29 14:08 UTC, josip2312 commented on src/store/index.js
> +      const scheduleId = state.schedules.findIndex((schedule) => {
This is not the schedule id, you're using the `findIndex` method

2022-03-29 14:08 UTC, josip2312 commented on src/store/index.js
> +    async editSchedule({ commit }, { id, schedule }) {
You already have the id inside the schedule object

also update related logic
```suggestion
    async editSchedule({ commit }, schedule) {
```

2022-03-29 14:08 UTC, josip2312 commented on src/store/index.js
> +      commit(UPDATE_SCHEDULE, { id, updatedSchedule });
In addition from above
```suggestion
      commit(UPDATE_SCHEDULE, updatedSchedule);
```

2022-03-29 14:08 UTC, josip2312 commented on src/store/index.js
> +      // set pagination
```suggestion
```

2022-03-29 14:08 UTC, josip2312 commented on src/store/index.js
> +      // set pagination
```suggestion
```

2022-03-29 14:08 UTC, josip2312 commented on src/store/index.js
> +      // set pagination
```suggestion
```

2022-04-01 09:40 UTC, josip2312 requested changes

2022-04-01 09:40 UTC, josip2312 commented on src/components/ModalCreateSchedule.vue
> +      return filteredMessages;
Use map here

2022-04-01 09:40 UTC, josip2312 commented on src/components/ModalCreateSchedule.vue
> +      return filteredMessages;
Use map here

2022-04-01 09:40 UTC, josip2312 commented on src/store/index.js
> +}
Pass an array here from the editSchedule action to avoid these checks

2022-04-01 09:40 UTC, josip2312 commented on src/store/index.js
> +}
Pass an array here from the editSchedule action to avoid these checks

2022-04-01 11:11 UTC, josip2312 approved these changes

2022-04-01 11:30 UTC, thedev966 approved these changes

2022-04-01 11:30 UTC, merged