Task/validation
scokljat/welcome-bot-frontend pull request #33
Opened 2022-04-04 12:10 UTC by thedev966

2022-04-04 12:52 UTC, scokljat approved these changes

2022-04-05 08:12 UTC, josip2312 requested changes

2022-04-05 08:12 UTC, josip2312 commented on src/components/AppSelect.vue
> +    errors: {
This prop is actually an error message, it is not plural?
so name it more appropriately

2022-04-05 09:27 UTC, josip2312 approved these changes

2022-04-05 09:44 UTC, merged